### ISSUE TITLE
Update hyperlink of official website to this repo

### ISSUE THREAD

**Issue by DjangoPeng** [coschain/contentos-go#1]
I noticed that the GitHub hyperlink of https://www.contentos.io/ is out of date, which linked to https://github.com/coschain/contentos, a deprecated C++ version of Contentos.

I'm not sure whether this golang version is ready. 
- If ready, just update the link.
- If not, don't update the description of C++ version.

At least we should keep one alive, otherwise it makes me sort of confused.

BTW: May I ask what's the reason of changing language?

**Comment by yykingking** [comment]
1.  The c++ version has been deprecated. We has updated the hyperlink in our official web page. Thanks for your carefulness.

2.  The golang version is under heavy developing , and the testate will be released before the end of Q1, 2019.

3.  Switching our main language is an effective way for sustainable development.

**Comment by DjangoPeng** [comment]
I c.
Good luck.
